### ISSUE TITLE
what should functions that test for conforming data return?

### ISSUE THREAD

**Issue by almartin82** [almartin82/mapvizieR#2]
When we put a CDF data frame through its paces to make sure that it is ready for use with visualization functions, what should those tests return?

they could just return T/F, but is there any harm in returning a named list - with the first element being the boolean result, and the second a more descriptive string describing what tests happened?

see [this function](https://github.com/almartin82/mapvizieR/blob/690f736cd8ffd31ecf9f791d5642d52bcb22f2c4/R/cdf_check.R#L24) for an example.

**Comment by chrishaid** [comment]
I think I'm a little confused as to what is happening here.  It seems like the 'check' functions are being conflated with 'test' functions a little bit. 

So I think 'test' fuctions are for development and provide developers with info about what when wrong when they break a unit test.  Then the some of that extra info you are suggesting is important.

I think 'check' functions on the other hand should be used to fail gracefully.  That is, if things don't conform in a functions argument (e.g., wrong columns) then the check_function throws an error with an informative message.  Otherwise I think the "check" function should return nothing/silently so that the the function it is supporting can chug along merrily.

**Comment by almartin82** [comment]
we talked about this over the phone. but to document it here- agreed that these are two separate things.  i guess I'm seeing the code reuse between 'check' and 'test' functions as largely a good thing.  tests will be a larger universe than the checks, but if we can reuse a 'check' function (that's mostly for workflow) in our tests, that's a nice bonus?
